# Configure the routing
info:
  component: Zuul server
  
spring:
  application:
    name: crm-gateway-service
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true 
   
zuul:
  routes:
    crm-customer-service: 
      path: /customer/**
      serviceId: crm-customer-service     
    crm-address-service: 
      path: /address/**
      serviceId: crm-address-service
    crm-product-service: 
      path: /product/**
      serviceId: crm-product-service
    crm-shop-service: 
      path: /shop/**
      serviceId: crm-shop-service
    
      

server:
  port: 8765   # HTTP (Tomcat) port