FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD crm-gateway-service-0.1.0.jar crm-gateway-service.jar
RUN sh -c 'touch /crm-gateway-service.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /crm-gateway-service.jar" ]
