
spring:
  application:
    name: crm-turbine-service
   
server:
  port: 8989
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    register-with-eureka: true 
  
turbine:
  appConfig: CRM-CUSTOMER-SERVICE,CRM-PRODUCT-SERVICE,CRM-SHOP-SERVICE
  clusterNameExpression: new String('default')
  combineHostPort: true